### PR TITLE
Fixes Code Analysis issues for C# templates

### PR DESCRIPTION
**Pull request by curia-damiano**
In my project I have enabled code analysis and found a couple of issues.
I would like to contribute updating the templates to benefit everyone.

### CODE REVIEW

**Comment by Takoooooo** [comment]
I guess these problems apply to F# templates too,may you add these fixes for them also?

**Comment by curia-damiano** [comment]
I'm sorry but I really don't know F#...

**Comment by Takoooooo** [comment]
Generally i am ok with everything besides identation changes,can they be reverted? I will add these changes to F# templates after that

**Comment by curia-damiano** [comment]
sorry I use tabs on my machine. I will work on this later

**Comment by curia-damiano** [comment]
About the Gretting variable, another option is to make it static, but probably this would change the meaning of the view model.

Or it can returns some non-static string

**Comment by curia-damiano** [comment]
I've fixed the formatting

**Review by Takoooooo — APPROVED** [review]

**Pull request merged**
