### PR TITLE
Added choice for net7.0

### PR DESCRIPTION
**Pull request by Mrxx99**
This adds the target framework choice for net7.0 additionally to the net6.0 for all templates.

One thing I noticed is that on CLI the parameter would be --Framework instead of --framework.
Should I adjust that like e.g. [it is done for the WPF template](https://github.com/dotnet/wpf/blob/main/packaging/Microsoft.Dotnet.Wpf.ProjectTemplates/content/WpfApplication-CSharp/.template.config/dotnetcli.host.json)?

Also should the test script also test both frameworks?

### CODE REVIEW

**Comment by Takoooooo** [comment]
I guess we need to test all available parameters in the test script for each template,but we can do that in the separate PR

**Comment by Mrxx99** [comment]
@Takoooooo I have one question: xplat projects currently target only net7.0 (without blazor). Should I add the blazor version back when net6.0 is selected? Or should net6.0 not supported for xplat?
One one hand you could say some people prefer LTS but on the other hand the whole xplat is preview so maybe we don't have to care.

**Comment by maxkatz6** [comment]
@Mrxx99 no, no need to support net6 for the xplat.
xplat template supports mobile which is only net7.

**Comment by Mrxx99** [comment]
@Takoooooo It should be ready now. I added the framework choosing like it is in WPF (the Framework override parameter allows setting a framework that is not one in the list, but the optin is hidden in both IDEs and CLI).
For the xplat template only net7.0 is choosable (it could be override with framework override to e.g. use early net8.0 previews)

**Comment by Takoooooo** [comment]
@Mrxx99 Sorry to ask,but can you revert previous commit and make xplat template to only target net7.0? I thought in WPF they just changed -Framework to appear as -framework in CLI just visually,but here we add some hidden option to override the TFM which is not what i want to add since our templates simply wont work if we would just change .net6.0 to net481 for example so this doesen't make much sense for me. Again.sorry for that,that's my fault

**Comment by Mrxx99** [comment]
@Takoooooo I have removed the --target-framework-override parameter, Xplat only targets net7.0 (it will show the version selector in VS, but only net7.0 is selectable)

**Review by Takoooooo — APPROVED** [review]
LGTM,will fix pipeline in a separate PR

**Pull request merged**
