### PR TITLE
Updated to rc2.2

### PR DESCRIPTION
**Pull request by Mrxx99**

### CODE REVIEW

**Comment by maxkatz6** [comment]
pending:
1. update android template @emmauss 
2. update to rc2.2

**Comment by Mrxx99** [comment]
Yes, already working on android fix, looking at the control catalog as reference

**Comment by Mrxx99** [comment]
Should the templates also have the Xamarin.AndroidX.Core.SplashScreen reference as the control catalog?

**Comment by emmauss** [comment]
> Should the templates also have the Xamarin.AndroidX.Core.SplashScreen reference as the control catalog?

Yes

**Comment by Mrxx99** [comment]
@emmauss I added the splash screen package, though it also seems to work without it.
The control catalog has some v31 resources, is the package needed for those? Should those also be added to the templates?

**Comment by emmauss** [comment]
> @emmauss I added the splash screen package, though it also seems to work without it. The control catalog has some v31 resources, is the package needed for those? Should those also be added to the templates?

Yes. Those are needed for the animated splash screen

**Comment by emmauss** [comment]
Without it, it will fail back to the static splash screen

**Comment by Mrxx99** [comment]
> > @emmauss I added the splash screen package, though it also seems to work without it. The control catalog has some v31 resources, is the package needed for those? Should those also be added to the templates?
> 
> Yes. Those are needed for the animated splash screen

done, if any other android adjustments are needed, you can add them maybe in a separate PR. The project files is the only thing different now.

**Review by emmauss — APPROVED** [review]

**Pull request merged**
